baseURL = "https://kirigamine.github.io/"
languageCode = "ja-jp"
title = "Polytopus"
theme = "pulp"
copyright = "© Polytopus"
hasCJKLanguage = true

[params]
  author = "Polytopus"
  avatar = "logo.png"
  description = """
    <ruby>多項<rt>たこ</rt></ruby>です。緑目の男とドラムンベースがすきです。<br />
    いろいろやってます。
  """
      publicationYear = "2025"

[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]
    
      [[menu.main]]
          identifier = "twitter"
          # name = "Twitter"
          pre = "<i class='fab fa-twitter fa-lg'></i>"
          url = "https://twitter.com/kiri_mist_fog"
          weight = 10

      [[menu.main]]
          identifier = "soundcloud"
          # name = "soundcloud"
          pre = "<i class='fab fa-soundcloud fa-lg'></i>"
          url = "https://soundcloud.com/polytopus"
          weight = 20

      [[menu.main]]
          identifier = "instagram"
          # name = "instagram"
          pre = "<i class='fab fa-instagram fa-lg'></i>"
          url = "https://www.instagram.com/polytopus_/"
          weight = 30
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

      [module]
[[module.mounts]]
source = "server"
target = "layouts"