baseURL = "https://kirichan.netlify.com/"
languageCode = "ja-jp"
title = "Kiri"
theme = "pulp"
copyright = "© Kiri"
twitterCardEnabled = true
hasCJKLanguage = true

[params]
  author = "きり"
  avatar = "logo.png"
  description = """
    きりです。おえかきとおんがくがすきです。<br />
    オリジナルの作品作ることもすきです。
  """
      publicationYear = "2020"

[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

      [[menu.main]]

      [[menu.main]]
          identifier = "twitter"
          # name = "Twitter"
          pre = "<i class='fab fa-twitter fa-lg'></i>"
          url = "https://twitter.com/kirichan_fog"
          weight = 20

      [[menu.main]]
          identifier = "soundcloud"
          # name = "soundcloud"
          pre = "<i class='fab fa-soundcloud fa-lg'></i>"
          url = "https://soundcloud.com/kirikirifoggy"
          weight = 40

      [[menu.main]]
          identifier = "instagram"
          # name = "instagram"
          pre = "<i class='fab fa-instagram fa-lg'></i>"
          url = "https://www.instagram.com/kiriwithpen/"
          weight = 50
